package com.example.orderUp_api.enums;

public enum OrderStatus {
    CREATED,
    ACCEPTED,
    CANCELLATION_REQUEST,
    CANCELLATION_REQUEST_REFUSED,
    CANCELLATION_REQUEST_ACCEPTED,
    PREPARED,
    DELIVERING,
    DELIVERED,
    NOT_RECEIVED,
    CANCELED,
    SUCCEED,
//    ORDER_REFUND_REQUEST,
//    ORDER_REFUND_ACCEPTED,
//    ORDER_REFUND_REFUSED
}
